#!/bin/sh

echo "Running docker-compose (down, pull & up)"

docker-compose -f docker-compose.yml down
docker-compose -f docker-compose.yml pull
docker-compose -f docker-compose.yml up -d

echo "Running docker-compose [Done]"

docker exec php-tutoring-app ./installer-run

exit 0
